// <auto-generated />
using System;
using Agendamento.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agendamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230913003651_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Agendamento.Model.Consulta", b =>
                {
                    b.Property<int?>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MedicoIdMedico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observações")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PacienteIdPaciente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RecepcionistaIdRecepcionista")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdConsulta");

                    b.HasIndex("MedicoIdMedico");

                    b.HasIndex("PacienteIdPaciente");

                    b.HasIndex("RecepcionistaIdRecepcionista");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Agendamento.Model.Especialidade", b =>
                {
                    b.Property<int?>("IdEspecialidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrição")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdEspecialidade");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Agendamento.Model.Medico", b =>
                {
                    b.Property<int?>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidade")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EspecialidadeIdEspecialidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NúmeroRegistroProfissional")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMedico");

                    b.HasIndex("EspecialidadeIdEspecialidade");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Agendamento.Model.Paciente", b =>
                {
                    b.Property<int?>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoricoMedico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NúmeroIdentificação")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPaciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Agendamento.Model.Recepcionista", b =>
                {
                    b.Property<int?>("IdRecepcionista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NúmeroIdentificação")
                        .HasColumnType("TEXT");

                    b.Property<string>("NúmeroTelefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.HasKey("IdRecepcionista");

                    b.ToTable("Recepcionistas");
                });

            modelBuilder.Entity("Agendamento.Model.Consulta", b =>
                {
                    b.HasOne("Agendamento.Model.Medico", "Medico")
                        .WithMany("ConsultasAgendadas")
                        .HasForeignKey("MedicoIdMedico");

                    b.HasOne("Agendamento.Model.Paciente", "Paciente")
                        .WithMany("ConsultasAgendadas")
                        .HasForeignKey("PacienteIdPaciente");

                    b.HasOne("Agendamento.Model.Recepcionista", null)
                        .WithMany("AgendamentosGerenciados")
                        .HasForeignKey("RecepcionistaIdRecepcionista");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Agendamento.Model.Medico", b =>
                {
                    b.HasOne("Agendamento.Model.Especialidade", null)
                        .WithMany("Medicos")
                        .HasForeignKey("EspecialidadeIdEspecialidade");
                });

            modelBuilder.Entity("Agendamento.Model.Especialidade", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("Agendamento.Model.Medico", b =>
                {
                    b.Navigation("ConsultasAgendadas");
                });

            modelBuilder.Entity("Agendamento.Model.Paciente", b =>
                {
                    b.Navigation("ConsultasAgendadas");
                });

            modelBuilder.Entity("Agendamento.Model.Recepcionista", b =>
                {
                    b.Navigation("AgendamentosGerenciados");
                });
#pragma warning restore 612, 618
        }
    }
}
